### PR TITLE
fix: ui update of homescreen

### LINKED ISSUE #89: Improve the UI of the homescreen
**Summary:**

There is a scope of UI improvement in the home screen of the app
Icons can be made smaller
Visit [this](https://dribbble.com/shots/7587490-MOLLET-Wallet-app-UI-Kit/attachments/372728?mode=media) for reference

**Steps to reproduce:**

Open the app

**Expected behaviour:**

Icons can be made smaller, Othe UI improvements will be appreciated

**Observed behaviour:**

Currently, the home screen has a scope of UI improvements

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open the app

**This issue is for GCI Students**

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #89 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@GOVINDDIXIT @jddeep @santoshconflux Please review and approve. Thanks

**Comment by sabya48** [comment]
Can i work on this to make it more better??

**Comment by sabya48** [comment]
@harshshinde07  can i work on this please

**Comment by harshshinde07** [comment]
Hi @sabya48 , the issue was created as a part of GCI for the students and the whole app needs redesign. So idk if it needs to be given more attention. @luckyman20 please look into it

**Comment by luckyman20** [comment]
Please refer #118

**Pull request closed without merging**
