### PR TITLE
Add currency symbols

### LINKED ISSUE #125: feat: Add currency symbol
**Summary:**

Wherever amount of money is displayed, the currency symbol is missing

**Steps to reproduce:**

Open Recent transactions or Accounts

**Expected behaviour:**

Add '$' sign before money values

**Observed behaviour:**

Currency symbol absent

**Screenshots:**

### PR DESCRIPTION
**Pull request by ashwinkey04**
Fixes #125 

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
You'll have to fetch the corresponding currency symbol from the API. It's not going to $ every time.

**Comment by ashwinkey04** [comment]
> You'll have to fetch the corresponding currency symbol from the API. It's not going to $ every time.

On it ;)

**Comment by garvit984** [comment]
@ashwinkey04 The currency has to be fetched with the help of API calls and not hardcoded. So can we please close this PR?

**Comment by ashwinkey04** [comment]
Can you provide me some inputs on fetching the currency symbol using the API? So that I can make necessary changes and submit my PR

**Comment by garvit984** [comment]
@ashwinkey04 You can have a look at this documentation https://demo.mifos.io/api-docs/apiLive.htm

**Pull request closed without merging**
