### PR TITLE
fix: Add app logo

### LINKED ISSUE #93: Add an app logo
**Summary:**
There should be an app logo just like mifos mobile app has.

### PR DESCRIPTION
**Pull request by refactor-droidyy**
Fixes #93 

Screenshot_2019-12-20-15-45-58-561_com miui home

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
hey @refactor-droidyy , the logo you have used is not official logo of Mifos Mobile CN. It is the logo of Mifos Initiative.

**Comment by refactor-droidyy** [comment]
@rachittt from where can i get the logo for mifos- mobile- cn ?

**Comment by rachittt** [comment]
> @rachittt from where can i get the logo for mifos- mobile- cn ?

I dont think there is any official logo as of now, so we can continue going with the default app icon.

**Comment by rachittt** [comment]
Closing this because of the reason stated above.

**Pull request closed without merging**
