### PR TITLE
Fix: Confirmation dialog in passcode activity

### LINKED ISSUE #86: Bug: Add a confirmation dialog in forgot passcode
**Summary:**
When user clicks on "Forgot passcode, login manually", he is directed to login page directly. However a cofirmation dialog should confirm whether he/she really wants to login manually. This will enhance the User Experience.

**Steps to reproduce:**
1. Go to Passcode Activity
2. Click on "Forgot passcode, login manually" button
3. You will be directed to the Login Activity

**Expected behaviour:**
Before directing to the login activity, a dialog should pop up to confirm the action.
**Observed behaviour:**
.No Confirmation takes place

**Device and Android version:**

Device - Mi A2 
Android 9 Pie

GIF:
ezgif com-video-to-gif (6)

### PR DESCRIPTION
**Pull request by rachittt**
Fixes #86 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
I think this can be closed now.

**Comment by rachittt** [comment]
this PR is particularly to solve the build fail.

**Comment by laxyapahuja** [comment]
@rachittt I am seeing a PR that solves the same issue authored by you which has been merged already.

**Comment by rachittt** [comment]
@laxyapahuja, if you try to see **carefully**, you'd notice that the build of the previous PR that had been merged has failed after getting merged. I am assuming it is because of the conflicting variable name. Therefore, I have changed the variable name in this PR so that when this gets merged, the build will be successful.

**Comment by rachittt** [comment]
i would change the title and squash the commits of this PR after some time.

**Pull request closed without merging**
