### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by sabya48**
Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by sabya48** [comment]
change in colour and lenght of username and password

**Comment by sabya48** [comment]
commit

**Comment by sabya48** [comment]
minor change

**Comment by garvit984** [comment]
@sabya48 Why there are so many commits in one PR?
Try to squash them into single commit.

**Comment by garvit984** [comment]
@sabya You are not following the contribution guidelines. First you should report a issue and also check for similar existing issues. Then you should make a PR with a single commit. If you want to work on issues reported by someone else, then you must ask that person if he is continuing that or not. If the persons says that he is no longer working on it, then only you can work on that issue.

**Comment by sabya48** [comment]
I am really sorry for that. I will squash all the commit into single.

**Comment by rachittt** [comment]
@sabya48 Hi, you have actually messed up the commits for this PR. It would be easier for you to close this PR and create a new one. Also, do not forget to **add the Issue Number and Screenshot** of your changes in the PR description. 
Thanks!

**Comment by rachittt** [comment]
hello @sabya48, if you do not fix this PR in the next three days, we will have to close it because of inactivity -- as it is restricting other contributors from fixing the issue.

**Comment by sabya48** [comment]
@rachittt i am sorry for for messing up all my commits. i will try to fix it as possible. i am having a problem in my PC. i will try to do it fast

**Comment by rachittt** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
