### PR TITLE
Ci/#195 setup ci using GitHub actions

### LINKED ISSUE #195: Add CI/CD GitHub Actions and remove other build checks
## Summary

The project currently has Travis. We need to remove this and use Github actions.
Following are the requirements:-

Generate the apk for every pull request and every commit on the redesign and master branch.
Build checks for every commit on any other branch.

### PR DESCRIPTION
**Pull request by Sparsh1212**
## Issue Fix
Fixes #195 
##

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by garvit984** [comment]
@abhijitramesh Can you please review it?

**Comment by garvit984** [comment]
@shiv07tiwari Can you please review it?

**Comment by garvit984** [comment]
@Sparsh1212 Please squash them into a single commit.

**Comment by Sparsh1212** [comment]
> @Sparsh1212 Please squash them into a single commit.
Done!

**Pull request closed without merging**
