### PR TITLE
redesign: Improve UI of Login Screen

### LINKED ISSUE #100: Redesign: Improve the UI of Login Screen
**Summary:**

There is a scope of UI Improvement in the login page. We should use material design.

**Expected outcome**

A visually appealing login page.

**Proposed Design:**

login-1

### PR DESCRIPTION
**Pull request by prajwal27**
Fixes #100 

**Summary**
Improve the UI of Login Screen. Also, virtual  keyboard to hide whenever clicked on the screen.

**Expected Behaviour**
ezgif com-video-to-gif (3)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by jawidMuhammadi** [comment]
Hey, @prajwal27 Your designed UI looks fantastic. But please keep in mind that whenever we design or redesign any screen we should keep the entire App's design consistent which is very important from material design and App's branding perspectives. For example, we have not used Outlined Edit Text in any other place inside the app and the background color does not have any relation with colorPrimary, colorPrimaryDark and colorAccent. So I recommend you to use Edit Texts without outline style and for background color use predefined colors or something very similar to them.

**Comment by prajwal27** [comment]
> Hey, @prajwal27 Your designed UI looks fantastic. But please keep in mind that whenever we design or redesign any screen we should keep the entire App's design consistent which is very important from material design and App's branding perspectives. For example, we have not used Outlined Edit Text in any other place inside the app and the background color does not have any relation with colorPrimary, colorPrimaryDark and colorAccent. So I recommend you to use Edit Texts without outline style and for background color use our predefined colors or something new but very similar to them.

@jawidMuhammadi since I had hoped to re-design only the login screen, theses inconsistencies are present.

**Comment by devansh-299** [comment]
@prajwal27 This task is meant to be performed during the GSoC period. I don't think you should work on it now

**Comment by rachittt** [comment]
@prajwal27, this PR is a duplicate of #110. We cannot consider this PR until #110 has been reviewed and closed therefore, closing this PR for now. We do appreciate your efforts though

**Pull request closed without merging**
