### PR TITLE
share functionality added

### LINKED ISSUE #72: feat: Implement share app feature in the application [GCI]
**Summary:**

Add the share app feature in the application

**Steps to reproduce:**

- Open the application
- Click on `Share` in the navigation drawer
- Nothing happens

**Expected behaviour:**

The task here is to add this functionality

### PR DESCRIPTION
**Pull request by rachittt**
Fixes #72 

GIF:
ezgif com-video-to-gif

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
@oorjitchowdhary thanks for showing interest in Mifos :)

**Comment by rachittt** [comment]
@SaumyaSingh1 i made this PR for a [task](https://codein.withgoogle.com/tasks/5886206831755264/?sp-organization=5721189306073088&sp-categories=1&sp-is_beginner=False&sp-search=Mifos%20Mobile%20%20share) which now seems to be removed now, can you look into it?

**Comment by SaumyaSingh1** [comment]
Hey @rachittt , Here is the task link : https://codein.withgoogle.com/dashboard/tasks/5886206831755264/

**Comment by SaumyaSingh1** [comment]
> @SaumyaSingh1 i made this PR for a [task](https://codein.withgoogle.com/tasks/5886206831755264/?sp-organization=5721189306073088&sp-categories=1&sp-is_beginner=False&sp-search=Mifos%20Mobile%20%20share) which now seems to be removed now, can you look into it?

The link you provided is opening for me . Recheck it : )

**Comment by SaumyaSingh1** [comment]
@rachittt  claim the task on GCI dashboard and submit your work there(provide the link of this P.R  ) .

**Comment by rachittt** [comment]
Screenshot (105)
The claim button does not work for this task(I do not have any pending task).
Even if you search it on [GCI website](https://codein.withgoogle.com/tasks/?sp-organization=5721189306073088&sp-search=share), it shows "no task found."
Can you help me with it ? @SaumyaSingh1

**Comment by SaumyaSingh1** [comment]
> Screenshot (105)
> The claim button does not work for this task(I do not have any pending task).
> Even if you search it on [GCI website](https://codein.withgoogle.com/tasks/?sp-organization=5721189306073088&sp-search=share), it shows "no task found."
> Can you help me with it ? @SaumyaSingh1

@rachittt  yes you will be able to claim it . Give me some time : )

**Comment by rachittt** [comment]
@SaumyaSingh1 hey, i have claimed and submitted this task now. Sorry for all the disruption caused earlier :)

**Pull request closed without merging**
